title: Hans Halwi # your name (or website title) here
logo: "/images/hans.jfif?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Currently kickstarting career switching to data-related roles, looking for opportunities for data related roles,
  especially in Analytics or Business Intelligence.
  <br><br>
  Hans is an enthusiastic learner and has good adaptability to new environments.
  Hans is willing to implement business knowledge, finance knowledge and data science related skills,
  to formulate the most effective, efficient and data-driven business strategies or decisions.
  <br><br>
  <a href="https://www.linkedin.com/in/hanshalwi/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
